services:
  backend:
    build: .
    ports:
      - "8080:8080"
      - "80:80"
    environment:
      NODE_ENV: production
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/src/app
    command: npm run start