services:
  proxydock:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "80:80"
    network_mode: bridge
    image: proxydock
    environment:
      NODE_ENV: production
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/app
    command: npm run start
